/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Software I2C Implementation
* Version           -> 1.0.0.0404
* Author            -> Hm @ Workstadion
* Build Date        -> 04.04.2019 06:11:45
* Description       -> **DEBUG** Version
*
*
*
*/

#include <avr/io.h>
#include <util/delay.h>

#include "i2csoft.h"


void I2cSoftInit( void ) 
{	
	_I2C_PORT &= ~( ( 1<<_I2C_SCL_BP ) | ( 1<<_I2C_SDA_BP ) );
	__PORT_DDR__( _I2C_PORT ) |= (( 1<<_I2C_SCL_BP ) | ( 1<<_I2C_SDA_BP ));	
}

void I2cSoftStart( void )
{
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SCL_BP ); // High
	H_DEL;
	
	__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SDA_BP ); // Low
	H_DEL;
}

void I2cSoftStop( void )
{
	
	__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SDA_BP ); // Low
	H_DEL;
	
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SCL_BP ); // High
	Q_DEL;
	
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SDA_BP ); // Low
	H_DEL;
}

uint8_t I2cSoftWrite( uint8_t Data )
{
	static uint8_t Acknowledge = 0;
	uint8_t ui;
	
	for ( ui = 0 ; ui < 8 ; ui++ )
	{
		__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); // Low
		
		Q_DEL;
		if ( Data & 0x80 )
		{
			__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SDA_BP ); // High
		}else
		{
			__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SDA_BP ); // Low
		}
		H_DEL;
		
		__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SCL_BP ); // High
		H_DEL;
		
 		while ( ( __PORT_PIN__( _I2C_PORT ) & ( 1<<_I2C_SCL_BP ) ) == 0 ); // Warten bis "Scl" Low..
		
		Data <<= 1;
	}

	//The 9th clock (ACK Phase)	
	__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); // Low
	Q_DEL;
	
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SDA_BP ); // High
	H_DEL;
	
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SCL_BP ); // High
	H_DEL;
		

	Acknowledge = !( __PORT_PIN__( _I2C_PORT ) & ( 1<<_I2C_SDA_BP ) );
	
	__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); // Low
	H_DEL;
	
	return Acknowledge;	
}

 
 uint8_t I2cSoftRead( uint8_t Acknowledge )
 {
	 uint8_t uiData = 0;
	 uint8_t ui;
	 
	 for ( ui = 0 ; ui < 8 ; ui++ )
	 {
		__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); // Low
		H_DEL;
		__PORT_DDR__( _I2C_PORT ) |=  ( 1<<_I2C_SCL_BP ); // High
		H_DEL;	

		while( ( __PORT_PIN__( _I2C_PORT ) & ( 1<<_I2C_SCL_BP ) ) == 0 );
		
		if( __PORT_PIN__( _I2C_PORT ) & ( 1<<_I2C_SDA_BP ) )
		{
			uiData |= ( 0x80 >> ui );
		}
	 }

	__PORT_DDR__ ( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); //Soft_I2C_Put_Ack
	Q_DEL;

	if ( Acknowledge )
	{
		__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SDA_BP ); // Low
	}else
	{
		__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SDA_BP ); // High
	}
	H_DEL;
	
	__PORT_DDR__( _I2C_PORT ) |= ( 1<<_I2C_SCL_BP ); // High
	H_DEL;
	
	__PORT_DDR__( _I2C_PORT ) &= ~( 1<<_I2C_SCL_BP ); // Low
	H_DEL;
			
	return uiData;
 }
 
















